### PR TITLE
Add infrastructure/Pulumi.test.yaml

### LINKED ISSUE #104: Clarify which app servers are required and which are legacy
There are multiple app servers, both frontend and backend running or stopped and we're not sure which ones we still need and which are legacy.

### PR DESCRIPTION
**Pull request by mhauru**
The Pulumi stack config file for our test deployment. Needs to be shared between everyone who wants to be able to manage the deployment. Should be fine to put under version control since all the secrets are encrypted with a key stored on Azure.

Closes #104

### CODE REVIEW

**Review by EdwinB12 — COMMENTED** [review]
Are you happy with the name of the file Markus? .test.yaml?

**Comment by mhauru** [comment]
That's the name of the pulumi stack. Could rename to `dev`?

**Comment by mhauru** [comment]
(A stack is Pulumi's idea of a deployment, like one for production and other for testing/development.)

**Comment by EdwinB12** [comment]
Ahh okay, apologies. Wan

**Review by EdwinB12 — APPROVED** [review]

**Comment by mhauru** [comment]
Oh I see, yeah that's just how Pulumi names those files. Not sure if that's the best name for the stack but let's go with it for now.

**Pull request merged**
