### PR TITLE
Switch to a pyproject.toml

### PR DESCRIPTION
**Pull request by mhauru**
Replacing setup.py and requirements.txt with pyproject.toml

### CODE REVIEW

**Comment by mhauru** [comment]
We need to change all the exactly pinned dependencies to lower bounds, but that's for later.

**Comment by EdwinB12** [comment]
resolves #110 

We should also document developers should install the dev packages too.

**Comment by EdwinB12** [comment]
I've made a few additions: 

- Changed the instructions in the developers documentation to install all the dependencies. 
- Changed the license tag to license-files and moved it to tool.setuptools as apparently this is best practice. 

I have asked some colleagues about how license and readme files are used. The readme file is parsed by PyPi so if we ever publish it to PyPi then I think the Readme displays on the front page maybe? 
However. nobody seemed to understand how the license file was used. As we have a seperate license file incorporated in the repository anyway, this should be included in any distribution i think. . 

Anyway, I think its good to go for now. 

@mhauru - Do you think we should all try and do a full install before merging? There are endpoints in this file. . . Or do we trust to CI to do this? 

I think regardless, @GiorgioCerro, it would be good if you could test the pip install your end. Instructions are [here](https://github.com/alan-turing-institute/DTBase/blob/main/DeveloperDocs.md).

**Review by EdwinB12 — APPROVED** [review]

**Comment by mhauru** [comment]
Thanks Edwin, looks good. I was heartened to see that the unit tests action fails if we make the package uninstallable, but would be happy to get any possible comments from @GiorgioCerro

**Comment by GiorgioCerro** [comment]
I am testing this now with a Windows laptop. If that works I think it is going to be a super thumbs up! 
Just checking, I saw @mhauru is working with a Macbook. What about you @EdwinB12 ? I hope all the packages are compatible with the three different OS

**Comment by mhauru** [comment]
Everyone in REG runs a Mac, so everything has been mostly tested on MacOS, although I would expect things to go smoothly on Linux too since it's so similar. Now Windows on the other hand I'm very interested to hear how it goes, I have very little understanding of how development works on Windows and this would be good feedback. If you have access to the Linux Subsystem for Windows thing that might come in handy if things don't work out of the box.

**Review by GiorgioCerro — APPROVED** [review]
The file looks good and everything went smooth on a Windows laptop with python version 3.10. 
Out of curiosity, why the upper bound to the python version? Is there any package which is not installable or is different on newer version of python?

**Comment by mhauru** [comment]
Yeah, there's a problem with the frozen scipy version: https://github.com/alan-turing-institute/DTBase/issues/91

Will hopefully sort that out and increase the range of compatible versions soon, as we go through relaxing dependency constraints in general.

**Pull request merged**
